import 'package:flutter/foundation.dart';

void registerNativeLibraryLicenses() {
  // ── mpv (libmpv-2.dll) ────────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['mpv (libmpv)'], '''
mpv is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.

Copyright (C) 2000-2025 mpv contributors.

  mpv is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with mpv. If not, see <https://www.gnu.org/licenses/lgpl-2.1.html>.
'''),
      ));

  // ── FFmpeg (ffmpeg-8.dll) ─────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['FFmpeg'], '''
FFmpeg is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.

Copyright (C) 2000-2025 FFmpeg Project contributors.

  FFmpeg is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with FFmpeg. If not, see <https://www.gnu.org/licenses/lgpl-2.1.html>.
'''),
      ));

  // ── libvlc / fvp (fvp.dll) ────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['libvlc (FVP)'], '''
libvlc is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.

Copyright (C) 1996-2025 VideoLAN and VLC contributors.

  libvlc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library. If not, see <https://www.gnu.org/licenses/lgpl-2.1.html>.
'''),
      ));

  // ── TDLib (tdjson.dll) ────────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['TDLib'], '''
Boost Software License - Version 1.0 - August 17th, 2003

Copyright (C) 2014-2025 Telegram Messenger Inc.

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

Full license: <https://www.boost.org/LICENSE_1_0.txt>
'''),
      ));

  // ── OpenSSL (libcrypto-3-x64.dll, libssl-3-x64.dll) ───────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['OpenSSL'], '''
Licensed under the Apache License 2.0 (the "License").
You may obtain a copy of the License at
<https://www.apache.org/licenses/LICENSE-2.0>.

Copyright (C) 1998-2025 The OpenSSL Project.
Copyright (C) 1995-1998 Eric A. Young, Tim J. Hudson.

  This product includes cryptographic software written by
  Eric Young (eay@cryptsoft.com).

  This product includes software developed by the OpenSSL Project
  for use in the OpenSSL Toolkit. (https://www.openssl.org/).

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'''),
      ));

  // ── zlib (zlib1.dll) ─────────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['zlib'], '''
zlib.h -- interface of the zlib general purpose compression library
Copyright (C) 1995-2024 Jean-loup Gailly and Mark Adler.

This software is provided "as-is", without any express or implied warranty.
In no event will the authors be held liable for any damages arising from
the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software.

  2. Altered source versions must be plainly marked as such, and must not
     be misrepresented as being the original software.

  3. This notice may not be removed or altered from any source distribution.

Full license: <https://www.zlib.net/zlib_license.html>
'''),
      ));

  // ── SQLite (sqlite3.dll) ─────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['SQLite'], '''
SQLite is in the Public Domain.

All of the code and documentation in SQLite has been dedicated to the
public domain by the authors. All code authors, and representatives of
the companies they work for, have signed affidavits dedicating their
contributions to the public domain and originals of those signed
affidavits are stored in a firesafe at the main offices of Hwaci.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute
the original SQLite code, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any means.

For more information: <https://www.sqlite.org/copyright.html>
'''),
      ));

  // ── libass (libass.dll) ───────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['libass'], '''
Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

Copyright (C) 2006-2025 libass contributors.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Full license (ISC): <https://opensource.org/licenses/ISC>
'''),
      ));

  // ── MDK (mdk.dll) ─────────────────────────────────────────────────
  LicenseRegistry.addLicense(() => Stream<LicenseEntry>.value(
        const LicenseEntryWithLineBreaks(<String>['MDK'], '''
MIT License

Copyright (C) Wang Bin (wbsecg1@gmail.com).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

Full license: <https://github.com/wang-bin/mdk-sdk>
'''),
      ));
}
